name: Docker Build Arm64

on:
    release:
      types: [published]
    push:
      branches: [ "main" ]
      # Publish semver tags as releases.
      tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          registry: docker.io
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}

    - name: Set release tag as image tag
      id: set-tag
    #   run: echo "::set-output name=TAG::${GITHUB_REF/refs\/tags\//}"
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          docker.io/cronicle/actions:${{ env.TAG }}
          docker.io/cronicle/actions:latest


